package no.fint.model.utdanning.vurdering;

import java.util.Arrays;
import java.util.List;

public enum VurderingActions {
	
	GET_SENSOR,
	GET_ALL_SENSOR,
	UPDATE_SENSOR,
	GET_ELEVFRAVAR,
	GET_ALL_ELEVFRAVAR,
	UPDATE_ELEVFRAVAR,
	GET_FRAVARSREGISTRERING,
	GET_ALL_FRAVARSREGISTRERING,
	UPDATE_FRAVARSREGISTRERING,
	GET_SLUTTORDENSVURDERING,
	GET_ALL_SLUTTORDENSVURDERING,
	UPDATE_SLUTTORDENSVURDERING,
	GET_HALVARSORDENSVURDERING,
	GET_ALL_HALVARSORDENSVURDERING,
	UPDATE_HALVARSORDENSVURDERING,
	GET_UNDERVEISORDENSVURDERING,
	GET_ALL_UNDERVEISORDENSVURDERING,
	UPDATE_UNDERVEISORDENSVURDERING,
	GET_FRAVARSOVERSIKT,
	GET_ALL_FRAVARSOVERSIKT,
	UPDATE_FRAVARSOVERSIKT,
	GET_ANMERKNINGER,
	GET_ALL_ANMERKNINGER,
	UPDATE_ANMERKNINGER,
	GET_KARAKTERHISTORIE,
	GET_ALL_KARAKTERHISTORIE,
	UPDATE_KARAKTERHISTORIE,
	GET_SLUTTFAGVURDERING,
	GET_ALL_SLUTTFAGVURDERING,
	UPDATE_SLUTTFAGVURDERING,
	GET_HALVARSFAGVURDERING,
	GET_ALL_HALVARSFAGVURDERING,
	UPDATE_HALVARSFAGVURDERING,
	GET_UNDERVEISFAGVURDERING,
	GET_ALL_UNDERVEISFAGVURDERING,
	UPDATE_UNDERVEISFAGVURDERING,
	GET_EKSAMENSGRUPPEMEDLEMSKAP,
	GET_ALL_EKSAMENSGRUPPEMEDLEMSKAP,
	UPDATE_EKSAMENSGRUPPEMEDLEMSKAP,
	GET_KARAKTERVERDI,
	GET_ALL_KARAKTERVERDI,
	UPDATE_KARAKTERVERDI,
	GET_EKSAMENSGRUPPE,
	GET_ALL_EKSAMENSGRUPPE,
	UPDATE_EKSAMENSGRUPPE,
	GET_FRAVAR,
	GET_ALL_FRAVAR,
	UPDATE_FRAVAR,
	GET_VURDERING,
	GET_ALL_VURDERING,
	UPDATE_VURDERING
	;


    /**
     * Gets a list of all enums as string
     *
     * @return A string list of all enums
     */
    public static List<String> getActions() {
        return Arrays.asList(
                Arrays.stream(VurderingActions.class.getEnumConstants()).map(Enum::name).toArray(String[]::new)
        );
    }

}

